# Site settings
baseurl = "http://robhar.com/"
languageCode = "en-us"
title = "Robert"
theme = "hugo-cactus-theme"
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
    name = "Robert den Harink"
    description = "Developer/Designer, I like solving problems"
    bio = "Code, music and travels"
    # Enter optionally your twitter account
    twitter = "@rauwekost"
    enableRSS = false

    # Add custom assets with their paths relative to the static folder
    customCSS = ["css/style.css"]
    customJS  = []

    # The variables below are optionally too and can be used to
    # translate or customize each string of the theme.

    # Navigation links
    home = ""
    about = ""
    subscribe = ""
    # Pagination links
    olderPosts = ""
    newerPosts = ""
    readMore = ""
    copyright = ""
    # Sharing options and author information in posts
    aboutAuthor = ""
    tweet = ""
    share = ""
    # 404 page
    title404 = ""
    subtitle404 = ""

    # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
    iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/rauwekost"
    github   = "https://www.github.com/rauwekost"

[taxonomies]
    tag = "tags"
    category = "categories"