name = "Robhar2016"
license = "MIT"
description = "A minimalistic and responsive theme for bloggers."
tags = ["blog", "disqus", "google analytics", "rss", "syntax highlighting"]
features = ["disqus", "google analytics", "rss", "syntax highlighting", "blog", "pagination", "<sharing options"]
min_version = 0.15

[author]
  name = "robert den harink"
  homepage = "//github.com/rauwekost"
